In [1]:
import pandas as pd
import numpy as np
import pickle

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB

In [42]:
#df = pd.read_pickle('trainWithtargetDF_fixed.pkl')
df = pd.read_pickle('trainWithtargetDF_fixed_normalised.pkl')

In [43]:
df.head()

ImageId   class_0  class_1  class_2  class_3  \
0  000001306cae19a89e295296b506bab7  0.499660      0.0      0.0      0.0   
1  000006419b6c05ec9cf30ef466dd8fec  0.912481      0.0      0.0      0.0   
2  000007d3372fb4688f870cb150d551f8  0.977087      0.0      0.0      0.0   
3  000010bc53c1c6c567c112b7a17227fa  0.034526      0.0      0.0      0.0   
4  00001a68648da02922172a45b42f5e16  0.000000      0.0      0.0      0.0   

   class_4  class_5  class_6  class_7  class_8  ...  class_71  class_72  \
0      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
1      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
2      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
3      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
4      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   

   class_73  class_74  class_75  class_76  class_77  class_78  class_79  \
0       0.0       0.0       0.0       0.0       0.0       0.0  0.000000   
1       0.0       0.0       0.0       0.0       0.0       0.0  0.058808   
2       0.0       0.0       0.0       0.0       0.0       0.0  0.000000   
3       0.0       0.0       0.0       0.0       0.0       0.0  0.000000   
4       0.0       0.0       0.0       0.0       0.0       0.0  0.000000   

   targetScore  
0     0.000000  
1     0.600000  
2     0.000000  
3     0.000000  
4     0.333333  

[5 rows x 82 columns]

In [14]:
X = df[df.columns[1:-1]].values

In [44]:
y = df[df.columns[-1]].values

In [16]:
del df

In [17]:
X[X>0.6] = 1
X[X<=0.6] = 0

In [47]:
y1 = y
y1[y1>0.5] = 1
y1[y1<=0.5] = 0

In [49]:
y1.max()

1.0

In [50]:
reg = GaussianNB().fit(X,y1)
reg.score(X, y1)

0.1501466792117665

In [51]:
pickle.dump(reg, open('gaussianBayes.pkl','wb'))

In [9]:
reg = LinearRegression().fit(X, y)
reg.score(X, y)

0.00023373155604267115

In [13]:
pickle.dump(reg, open('linearClassifier.pkl','wb'))

# Validate on Train dataset

In [41]:
yActual = reg.predict(X)

In [42]:
newDF = df[['ImageId']]

In [43]:
newDF['actualScore'] = yActual

/home/adeykin/miniconda3/envs/sna_hackaton_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [45]:
newDF.to_pickle('trainValidateOnTrainDF.pkl')

# Test

In [52]:
df = pd.read_pickle('testDF_fixed.pkl')
df.head()

fileName   class_0  class_1  class_2  class_3  \
0  0000247ff80ff7ba0eda80b611fec196  0.000000      0.0      0.0      0.0   
1  000042fffe32f5b13211e9e6e44e5402  0.000000      0.0      0.0      0.0   
2  0000d2dacea1db87d58336b5a3411724  0.011461      0.0      0.0      0.0   
3  0000e46b41cdfa07fc87bf34434df10c  0.000000      0.0      0.0      0.0   
4  00010a1fb0f14cf2e2acd1a94bfa3a58  0.000000      0.0      0.0      0.0   

   class_4  class_5  class_6  class_7  class_8  ...  class_70  class_71  \
0      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
1      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
2      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
3      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   
4      0.0      0.0      0.0      0.0      0.0  ...       0.0       0.0   

   class_72  class_73  class_74  class_75  class_76  class_77  class_78  \
0       0.0       0.0       0.0  0.000000       0.0  0.000000       0.0   
1       0.0       0.0       0.0  0.000000       0.0  0.000000       0.0   
2       0.0       0.0       0.0  0.000000       0.0  0.000000       0.0   
3       0.0       0.0       0.0  0.000000       0.0  0.030499       0.0   
4       0.0       0.0       0.0  0.245938       0.0  0.000000       0.0   

   class_79  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 81 columns]

In [53]:
Xtest = df[df.columns[1:]].values

In [54]:
Xtest[Xtest>0.6] = 1
Xtest[Xtest<=0.6] = 0

In [60]:
ytest = reg.predict_proba(Xtest)

In [61]:
ytest.max()

1.0

In [62]:
df['score'] = ytest

In [63]:
testDF = df[['fileName','score']]

In [64]:
testDF.head()

fileName     score
0  0000247ff80ff7ba0eda80b611fec196  0.019393
1  000042fffe32f5b13211e9e6e44e5402  0.019393
2  0000d2dacea1db87d58336b5a3411724  0.019393
3  0000e46b41cdfa07fc87bf34434df10c  0.019393
4  00010a1fb0f14cf2e2acd1a94bfa3a58  0.019393

In [65]:
testDF.to_pickle('predictGaussianBayes.pkl')

In [21]:
testDF.to_pickle('predictLinear.pkl')

In [16]:
np.sum(X > 1)

0

In [17]:
print(X.max())
print(X.min())

0.99905545
0.0


In [27]:
X[X<0.6] = 0

In [33]:
X[X>0] = 1

In [34]:
X[3,:]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [36]:
s = X.sum(axis=0)
s

array([3.79853e+05, 1.16800e+03, 3.67720e+04, 3.37600e+03, 3.21200e+03,
       1.94900e+03, 1.22000e+03, 9.57600e+03, 2.49400e+03, 7.22000e+02,
       3.58000e+02, 4.19000e+02, 6.90000e+01, 1.87300e+03, 9.60100e+03,
       3.04750e+04, 3.09800e+04, 3.92600e+03, 1.06100e+03, 1.10600e+03,
       6.24000e+02, 2.45200e+03, 2.26000e+02, 2.70000e+02, 2.16000e+02,
       1.72600e+03, 1.20200e+03, 1.64690e+04, 8.07000e+02, 1.18600e+03,
       2.18000e+02, 1.53000e+02, 3.47200e+03, 1.60200e+03, 1.02000e+02,
       1.51000e+02, 3.07000e+02, 3.56000e+02, 1.53000e+02, 8.41500e+03,
       1.99400e+03, 1.15130e+04, 1.47200e+03, 5.50000e+02, 1.46500e+03,
       1.56500e+04, 7.18000e+02, 1.37600e+03, 2.98700e+03, 1.83000e+03,
       6.51000e+02, 9.04000e+02, 6.56000e+02, 5.58600e+03, 3.48100e+03,
       1.33460e+04, 7.37500e+03, 4.27200e+03, 6.34300e+03, 6.59200e+03,
       4.45000e+03, 9.12000e+02, 5.09400e+03, 1.99900e+03, 3.03000e+02,
       7.43000e+02, 4.48000e+02, 4.49000e+03, 5.51000e+02, 9.230

In [42]:
s.argsort()

array([70, 78, 12, 34, 35, 38, 31, 79, 24, 30, 22, 23, 64, 36, 76, 37, 10,
       11, 66, 43, 68, 20, 50, 52, 46,  9, 65, 71, 28, 51, 61, 69, 18, 19,
        1, 29, 26,  6, 72, 47, 44, 42, 33, 25, 49, 13,  5, 40, 63, 21,  8,
       48, 73,  4, 74,  3, 32, 54, 17, 57, 60, 67, 77, 62, 53, 58, 59, 75,
       56, 39,  7, 14, 41, 55, 45, 27, 15, 16,  2,  0])

In [43]:
s.sort()

In [44]:
s

array([0.00000e+00, 0.00000e+00, 6.90000e+01, 1.02000e+02, 1.51000e+02,
       1.53000e+02, 1.53000e+02, 1.78000e+02, 2.16000e+02, 2.18000e+02,
       2.26000e+02, 2.70000e+02, 3.03000e+02, 3.07000e+02, 3.15000e+02,
       3.56000e+02, 3.58000e+02, 4.19000e+02, 4.48000e+02, 5.50000e+02,
       5.51000e+02, 6.24000e+02, 6.51000e+02, 6.56000e+02, 7.18000e+02,
       7.22000e+02, 7.43000e+02, 7.61000e+02, 8.07000e+02, 9.04000e+02,
       9.12000e+02, 9.23000e+02, 1.06100e+03, 1.10600e+03, 1.16800e+03,
       1.18600e+03, 1.20200e+03, 1.22000e+03, 1.25200e+03, 1.37600e+03,
       1.46500e+03, 1.47200e+03, 1.60200e+03, 1.72600e+03, 1.83000e+03,
       1.87300e+03, 1.94900e+03, 1.99400e+03, 1.99900e+03, 2.45200e+03,
       2.49400e+03, 2.98700e+03, 3.20900e+03, 3.21200e+03, 3.30800e+03,
       3.37600e+03, 3.47200e+03, 3.48100e+03, 3.92600e+03, 4.27200e+03,
       4.45000e+03, 4.49000e+03, 4.93900e+03, 5.09400e+03, 5.58600e+03,
       6.34300e+03, 6.59200e+03, 6.82600e+03, 7.37500e+03, 8.415

Most common: person, car, cat, dog, tie, bowl
Less common: parking meter, baseball bat, baseball glave, tennis racket
Never apperas: toaster, hair drier

In [8]:
print(Xtest.min())
print(Xtest.max())

0.0
0.9988829


In [9]:
Xtest[Xtest<0.6] = 0
Xtest[Xtest>=0.6] = 1

In [24]:
Xtest.sum(axis=1)[0:20]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 0., 1.], dtype=float32)

In [32]:
Xtest[19]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [20]:
df

fileName   class_0   class_1   class_2  \
0       0000247ff80ff7ba0eda80b611fec196  0.000000  0.000000  0.000000   
1       000042fffe32f5b13211e9e6e44e5402  0.000000  0.000000  0.000000   
2       0000d2dacea1db87d58336b5a3411724  0.011461  0.000000  0.000000   
3       0000e46b41cdfa07fc87bf34434df10c  0.000000  0.000000  0.000000   
4       00010a1fb0f14cf2e2acd1a94bfa3a58  0.000000  0.000000  0.000000   
5       0001342fab36bfb25799e7a06f313b99  0.650508  0.000000  0.146382   
6       00015e88eaab7b82715634aa0d94e4c3  0.000000  0.000000  0.000000   
7       0001b4a10d1a9e95fe892709dd5b1f77  0.000000  0.000000  0.000000   
8       0001bc02f2c701aaed3ad93869007aed  0.000000  0.000000  0.000000   
9       0001d6ef22e79efa27a5ee8b4e1f96fe  0.000000  0.000000  0.000000   
10      000223224e839d0326cca02363d0691a  0.000000  0.000000  0.000000   
11      00024ff9a6718c6accc45bd9fb411b66  0.000000  0.000000  0.000000   
12      00025f4d8efc1528dc73cb74cd7d5125  0.924880  0.000000  0.000000   
13      00027f1ebb26f53b45d7e4a5c234cae8  0.089707  0.000000  0.000000   
14      00029b34539ce122831447a0d3d0d107  0.678365  0.000000  0.000000   
15      0002df5d5d557a88e92241112cb8fbb1  0.000000  0.000000  0.000000   
16      0003019698795d78b8a0ea26b3ebe586  0.426026  0.000000  0.000000   
17      00034a41e9686e8e79c656bbf771abff  0.210453  0.000000  0.000000   
18      000358b0f77efac8c47c3db6e9769546  0.000000  0.000000  0.000000   
19      00038198570ad8a93d441a56e9000ddb  0.854182  0.000000  0.000000   
20      00038ec615226182d2a6469efaf96e60  0.000000  0.000000  0.000000   
21      00039042bc6b7b43999ba127d6a6c8ec  0.017589  0.000000  0.000000   
22      0003ee1dac540a7e908b43c393156e72  0.242818  0.000000  0.000000   
23      0004191608277b90b179ccd0de617b0a  0.000000  0.000000  0.038495   
24      000431ad973a9a0d3b48f18176463dc9  0.000000  0.000000  0.000000   
25      000464f72f1300406b922ddc8a45211f  0.045797  0.000000  0.015501   
26      000470f1dc92cbce699c1311849395d3  0.000000  0.000000  0.000000   
27      0004c64345a710ee0a857052e04c0c23  0.918534  0.000000  0.000000   
28      0004fe0fdf1e6fb3955f8b7d3176d379  0.279962  0.000000  0.000000   
29      000546a5d0f8aebb8827fd9aff3a2fb0  0.307386  0.000000  0.000000   
...                                  ...       ...       ...       ...   
352475  ffe86d0162aa24acb3c88a5f8d84f268  0.000000  0.064589  0.000000   
352476  ffe886a268bb1836f16236a65f47ab85  0.000000  0.000000  0.000000   
352477  ffe8a6a7dee2967c66dfc1cd05ad816d  0.000000  0.000000  0.000000   
352478  ffe8b6bfaf8e92cf6cfb25fb72dcabaf  0.040620  0.000000  0.000000   
352479  ffe8be62cbb94ff2c124acdc4d34f560  0.000000  0.000000  0.000000   
352480  ffe8cae947ff07df735a3a42b2285e82  0.000000  0.000000  0.000000   
352481  ffe92570c0556be138dba7d708e4e5ec  0.000000  0.000000  0.000000   
352482  ffe973869d614b9ce0860e364b77f50e  0.000000  0.000000  0.000000   
352483  ffe9dd9d1fcc25d22c2217ea32d881d8  0.000000  0.000000  0.000000   
352484  ffeb12323dc95150042f4ed63c1512c6  0.917532  0.000000  0.000000   
352485  ffeb6a0ffe0c83778816badc4dc0663a  0.017925  0.000000  0.000000   
352486  ffeb8577ddb1c02ed8a385c8e40be4cd  0.000000  0.000000  0.000000   
352487  ffeb876bf8dfc1051998c2150c5cbb43  0.000000  0.000000  0.000000   
352488  ffebc03ca94a237e529654984c9a2db8  0.000000  0.000000  0.000000   
352489  ffec8ccb7daac919ab62993d6f12a98f  0.000000  0.000000  0.000000   
352490  ffed275a386e151f012237d70fbefc3a  0.880835  0.063930  0.000000   
352491  ffedaa4db54ff7fac1b700d3e41f241b  0.541873  0.000000  0.000000   
352492  ffedf199c0af4488433ba0afdc8bcb66  0.423225  0.000000  0.000000   
352493  ffee2fb15c3d9f33975c1d1caeccdece  0.868784  0.045537  0.000000   
352494  ffee3c8801775ea963244a0db586740d  0.047632  0.000000  0.000000   
352495  ffee703b036f084938e17938163bd177  0.640766  0.000000  0.000000   
352496  ffee8995760c28e77ef139424e666760  0.984835  0.000000  0.000000   
352497  ffeebd02d3f91a240dc148f5a596